#!/bin/bash
# Add a -x to the end of the above line to help debug this script.

# Set up prefix templates for pandoc-crossref.
ept='$$i$$'
spt='$$p$$$$i$$'

NAME=self_repl_fns
FLAGS="-s -S -M figPrefix=figure -M secPrefix="§" -M secPrefixTemplate="${spt}" -M eqnPrefixTemplate="${ept}" --filter pandoc-crossref -M eqnPrefix='' -M linkcolor=black --number-sections --bibliography=${NAME}.bib ${NAME}.md"

# Make and open the html file.
pandoc --mathjax --template=template.html ${FLAGS} > ${NAME}.html
# Move captions to be before figures in the html file.
TMP=$(mktemp tmp_XXXX)
cat ${NAME}.html | awk '{if(x) { print $0; print x; x = "" } else if (/<img/) { x = $0 } else { print $0 }}' > ${TMP}
mv ${TMP} ${NAME}.html
open ${NAME}.html

# Make and open the pdf file.
pandoc -t latex -o ${NAME}.tex -s ${FLAGS}
TMP=$(mktemp tmp_XXXX)
sed 's|images/\(.*\)\.png|images/pdfs/\1.pdf|' self_repl_fns.tex > ${TMP}
mv ${TMP} ${NAME}.tex
pdflatex ${NAME}.tex
open ${NAME}.pdf
