#!/bin/bash -x
# Add a -x to the end of the above line to help debug this script.

# Set up prefix templates for pandoc-crossref.
ept='$$i$$'
spt='$$p$$$$i$$'

name=lego_puzzle
# If I want a table of contents, I could add a --toc flag here.
FLAGS="-s -M figPrefix=figure -M secPrefix="§" -M secPrefixTemplate="${spt}" --filter pandoc-crossref -M eqnPrefix= -M linkcolor=black --number-sections --citeproc --bibliography=${name}.bib --lua-filter=filter.lua ${name}.md"

TMP=$(mktemp tmp_XXXX)

# Make the html file.
pandoc --mathjax --template=template.html ${FLAGS} > ${name}.html
sed 's|<li><ul>|<li style="list-style-type: none;"><ul>|' ${name}.html > ${TMP}
mv ${TMP} ${name}.html
chmod 644 ${name}.html

# Make and open the pdf file.
pandoc -t latex -o ${name}.tex -s ${FLAGS} --template=template.tex

sed 's|img/\(.*\)\.svg|img/\1.pdf|' ${name}.tex |\
sed 's|includegraphics{img/img3|includegraphics[width=0.3\\textwidth]{img/img3|' |\
sed 's|includegraphics{img/ann|includegraphics[width=0.32\\textwidth]{img/ann|' |\
sed 's|includegraphics{img/pie|includegraphics[width=0.8\\textwidth]{img/pie|' |\
sed 's|includegraphics{img/puz|includegraphics[width=0.8\\textwidth]{img/puz|' |\
sed 's|includegraphics{img/hom|includegraphics[width=0.72\\textwidth]{img/hom|' |\
sed 's|0.5\(.*home_model\)|0.7\1|' > ${TMP}

# This command used to be second in the chain above.
#sed 's|includegraphics{|includegraphics[width=0.5\\textwidth]{|' |\

# sed 's|img/\(.*\)\.svg|img/\1.pdf|' ${name}.tex > ${TMP}
# mv ${TMP} ${name}.tex
# sed 's|includegraphics{|includegraphics[width=0.5\\textwidth]{|' ${name}.tex > ${TMP}
## sed 's|graphics{img/\(.*\.svg\)|svg{img/\1|' ${name}.tex > ${TMP}
mv ${TMP} ${name}.tex
cat ${name}.tex <(echo) | sed '{N;s/\\item.*itemize.*/\\item[]\\begin{itemize}/;P;D;}' > ${TMP}
mv ${TMP} ${name}.tex
cat ${name}.tex <(echo) | sed 's/^\(\\includegraphics.*\)/\\begin{center}\1\\end{center}/' > ${TMP}
mv ${TMP} ${name}.tex

# sed 's|images/\(.*\)\.png|images/pdfs/\1.pdf|' ${name}.tex > ${TMP}
# awk -f tex_edits.awk ${name}.tex > ${TMP}
# mv ${TMP} ${name}.tex
pdflatex ${name}.tex

# XXX
exit

# Move captions to be before figures in the html file.
TMP=$(mktemp tmp_XXXX)
cat ${name}.html | awk '{if(x) { print $0; print x; x = "" } else if (/<img/) { x = $0 } else { print $0 }}' > ${TMP}
mv ${TMP} ${name}.html
#open ${name}.html

# Make a local-only version of the html for the author to work with.
sed 's_https://cdn.mathjax.org/mathjax/latest_'${HOME}/Dropbox/Documents/code/MathJax_ ${name}.html > ${name}_local.html
#open ${name}_local.html

# Make and open the pdf file.
pandoc -t latex -o ${name}.tex -s ${FLAGS} --template=template.tex
TMP=$(mktemp tmp_XXXX)
sed 's|images/\(.*\)\.png|images/pdfs/\1.pdf|' ${name}.tex > ${TMP}
mv ${TMP} ${name}.tex
pdflatex ${name}.tex
#open ${name}.pdf

# Make the kindle-friendly pdf file.
pandoc -t latex -o ${name}.tex -s ${FLAGS} --template=kindle_template.tex
TMP=$(mktemp tmp_XXXX)
sed 's|images/\(.*\)\.png|images/pdfs/\1.pdf|' ${name}.tex > ${TMP}
TMP2=$(mktemp tmp_XXXX)
# This next line is a hacky way to modify the definition of \zerotwo so that
# it looks better in this output format.
sed 's|\(\\newcommand{\\zerotwo}.*\)\\!|\1|;s|\(\\lower1pt\\hbox.*\)\\!|\1|' ${TMP} > ${TMP2}
rm ${TMP}
mv ${TMP2} ${name}_for_kindle.tex
pdflatex ${name}_for_kindle.tex
#open ${name}_for_kindle.pdf
