#!/bin/bash

if [ -z $1 ]; then
  echo Usage: makepdf [new_filename_no_ext]
  echo   Copies over svg.svg and runs cairosvg on it to convert it to a pdf.
  exit 0
fi

mv ~/Downloads/svg.svg $1.svg
cairosvg $1.svg -o $1.pdf
