#!/bin/bash
# Add a -x to the end of the above line to help debug this script.

# Set up prefix templates for pandoc-crossref.
ept='$$i$$'
spt='$$p$$$$i$$'
crossref_flags="-M figPrefix=figure -M secPrefix=§ -M secPrefixTemplate=${spt} -M eqnPrefixTemplate=${ept} --filter pandoc-crossref"

NAME=enum_comb
FLAGS="-s -S ${crossref_flags} -M linkcolor=black --bibliography=${NAME}.bib ${NAME}.md"

# Make and open the html file.
pandoc --mathjax --template=template.html ${FLAGS} > ${NAME}.html
# Uncomment this next bit to make caption-ordering compatible with tufte-edited.css.
# Move captions to be before figures in the html file.
#TMP=$(mktemp tmp_XXXX)
#cat ${NAME}.html | awk '{if(x) { print $0; print x; x = "" } else if (/<img/) { x = $0 } else { print $0 }}' > ${TMP}
#mv ${TMP} ${NAME}.html
open ${NAME}.html

# Make and open the pdf file.
pandoc -t latex -o ${NAME}.tex -s ${FLAGS}
TMP=$(mktemp tmp_XXXX)
sed 's|images/\(.*\)\.png|images/pdfs/\1.pdf|' ${NAME}.tex > ${TMP}
mv ${TMP} ${NAME}.tex
pdflatex ${NAME}.tex
